In [1]:
import numpy as nu
from galpy.potential import SCFPotential,PowerSphericalPotentialwCutoff, MiyamotoNagaiPotential
from galpy import potential
from SCFAnalysis.Constants import *
from SCFAnalysis.func import *
from galpy.util.bovy_coords import rect_to_cyl

from astropy import units

In [4]:
folder = ["SCF_Acos_N30_L30", "SCF_Acos2_N30_L30", "SCF_Acos3_N30_L30", "SCF_AcosFull_N30_L30"]
forces = getForces(folder)

In [5]:
print forces

[[ -2.22530330e-06  -4.66998684e-09   0.00000000e+00]
 [ -2.22514153e-06  -3.07805739e-08   0.00000000e+00]
 [ -2.22525098e-06  -1.27913972e-08   0.00000000e+00]
 [ -2.22543242e-06   1.63287269e-08   0.00000000e+00]]


In [16]:
amp = (forces[:,0] + forces[:,1])/(forces[0,0] + forces[0,1]) ## amp/2 (F_R' + F_z') =1/2* (F_R + F_z)
print amp

[ 1.          1.01163638  1.00361847  0.99064132]


In [18]:
## amp/4 (F_R'^2 + F_z'^2)^.5 =1/4* (F_R^2 + F_z^2)^.5
amp = (forces[:,0]**2 + forces[:,1]**2)**-.5 * (forces[0,0]**2 + forces[0,1]**2)**.5
print amp

[ 1.          0.99997924  1.00000919  0.99991727]
