In [1]:
import numpy as nu
from galpy.potential import SCFPotential,PowerSphericalPotentialwCutoff, MiyamotoNagaiPotential
from galpy import potential
from SCFAnalysis.Constants import *
from SCFAnalysis.func import *
from galpy.util.bovy_coords import rect_to_cyl

from astropy import units

In [2]:
folder = ["SCF_Acos_N30_L30", "SCF_Acos2_N30_L30", "SCF_Acos3_N30_L30", "SCF_AcosFull_N30_L30"]
forces = getForces(folder)

(R,z,phi) = (3000.00017547, 0.0294186787491, 6.28284328425)
(R,z,phi) = (3000.00017547, 0.0294186795847, 6.28284328425)
(R,z,phi) = (3000.00017547, 0.0294186800454, 6.28284328425)
(R,z,phi) = (3000.00017547, 0.0294186871919, 6.28284328425)


In [3]:
print forces

[[ -2.22531799e-06  -2.85868090e-11   0.00000000e+00]
 [ -2.22531724e-06  -2.61396821e-08   0.00000000e+00]
 [ -2.22531775e-06  -8.15015117e-09   0.00000000e+00]
 [ -2.22531860e-06   2.09705428e-08   0.00000000e+00]]


In [4]:
amp = (forces[:,0] + forces[:,1])/(forces[0,0] + forces[0,1]) ## amp/2 (F_R' + F_z') =1/2* (F_R + F_z)
print amp

[ 1.          1.01173316  1.00364946  0.99056393]


In [5]:
## amp/4 (F_R'^2 + F_z'^2)^.5 =1/4* (F_R^2 + F_z^2)^.5
amp = (forces[:,0]**2 + forces[:,1]**2)**-.5 * (forces[0,0]**2 + forces[0,1]**2)**.5
print amp

[ 1.          0.99993136  0.9999934   0.99995533]
